name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dist
      run: ls -al
    - name: dir
      run: mkdir out
    - name: build
      run: g++ -o out -I TestProg/TestProg/*.cpp
