name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dist
      run: ls -al
    - name: build 
      run: cd TestProg/TestProg/ 
           g++ -g $(find RootFolderName -type f -iregex ".\*.cpp") -o OutputName
      
